<?php
/**
 * Lumination Quiz Generator — Admin Settings Tab
 *
 * Registers plugin options and renders the Quiz Generator tab inside
 * the Lumination Core admin panel.
 *
 * @package    LuminationQuizGenerator
 * @since      1.0.0
 * @license    GPL-3.0-or-later
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Lumination_Quiz_Settings {

	/**
	 * Register settings with WordPress.
	 */
	public static function register_settings() {
		register_setting( 'lumination_qg_settings', 'lumination_qg_default_count', array(
			'type'              => 'integer',
			'sanitize_callback' => array( __CLASS__, 'sanitize_count' ),
			'default'           => 10,
		) );
		register_setting( 'lumination_qg_settings', 'lumination_qg_default_difficulty', array(
			'type'              => 'string',
			'sanitize_callback' => array( __CLASS__, 'sanitize_difficulty' ),
			'default'           => 'intermediate',
		) );
	}

	/**
	 * Sanitise the question count option.
	 *
	 * @param  mixed $value Raw value.
	 * @return int
	 */
	public static function sanitize_count( $value ) {
		$value = absint( $value );
		return max( 3, min( 30, $value ) );
	}

	/**
	 * Sanitise the difficulty option.
	 *
	 * @param  string $value Raw value.
	 * @return string
	 */
	public static function sanitize_difficulty( $value ) {
		$allowed = array( 'easy', 'intermediate', 'advanced' );
		return in_array( $value, $allowed, true ) ? $value : 'intermediate';
	}

	/**
	 * Render the Quiz Generator admin tab.
	 */
	public static function render_tab() {
		settings_errors( 'lumination_qg_messages' );
		$current_count      = (int) get_option( 'lumination_qg_default_count', 10 );
		$current_difficulty = get_option( 'lumination_qg_default_difficulty', 'intermediate' );
		?>
		<form action="options.php" method="post" style="max-width: 800px;">
			<?php settings_fields( 'lumination_qg_settings' ); ?>

			<h2><?php esc_html_e( 'Default Settings', 'lumination-quiz-generator' ); ?></h2>
			<table class="form-table" role="presentation">
				<tr>
					<th scope="row">
						<label for="lumination_qg_default_count"><?php esc_html_e( 'Default Question Count', 'lumination-quiz-generator' ); ?></label>
					</th>
					<td>
						<input type="number" id="lumination_qg_default_count" name="lumination_qg_default_count"
						       value="<?php echo esc_attr( $current_count ); ?>" min="3" max="30" step="1" style="width:80px;" />
						<p class="description"><?php esc_html_e( 'Number of questions generated by default (3-30). Users can override per quiz.', 'lumination-quiz-generator' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<label for="lumination_qg_default_difficulty"><?php esc_html_e( 'Default Difficulty', 'lumination-quiz-generator' ); ?></label>
					</th>
					<td>
						<select id="lumination_qg_default_difficulty" name="lumination_qg_default_difficulty">
							<option value="easy"         <?php selected( $current_difficulty, 'easy' ); ?>><?php esc_html_e( 'Easy', 'lumination-quiz-generator' ); ?></option>
							<option value="intermediate" <?php selected( $current_difficulty, 'intermediate' ); ?>><?php esc_html_e( 'Intermediate', 'lumination-quiz-generator' ); ?></option>
							<option value="advanced"     <?php selected( $current_difficulty, 'advanced' ); ?>><?php esc_html_e( 'Advanced', 'lumination-quiz-generator' ); ?></option>
						</select>
						<p class="description"><?php esc_html_e( 'Default difficulty level. Users can override per quiz.', 'lumination-quiz-generator' ); ?></p>
					</td>
				</tr>
			</table>

			<?php submit_button( __( 'Save Settings', 'lumination-quiz-generator' ) ); ?>
		</form>

		<hr />

		<h2><?php esc_html_e( 'Shortcode Usage', 'lumination-quiz-generator' ); ?></h2>
		<p><?php esc_html_e( 'Use the [lumination_quiz] shortcode on any page or post:', 'lumination-quiz-generator' ); ?></p>

		<table class="widefat striped" style="max-width: 800px;">
			<thead>
				<tr>
					<th><?php esc_html_e( 'Use Case', 'lumination-quiz-generator' ); ?></th>
					<th><?php esc_html_e( 'Shortcode', 'lumination-quiz-generator' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><?php esc_html_e( 'All Input Modes (tabbed)', 'lumination-quiz-generator' ); ?></td>
					<td><code>[lumination_quiz]</code></td>
				</tr>
				<tr>
					<td><?php esc_html_e( 'URL Only', 'lumination-quiz-generator' ); ?></td>
					<td><code>[lumination_quiz mode="url"]</code></td>
				</tr>
				<tr>
					<td><?php esc_html_e( 'Text Only', 'lumination-quiz-generator' ); ?></td>
					<td><code>[lumination_quiz mode="text"]</code></td>
				</tr>
				<tr>
					<td><?php esc_html_e( 'File Upload Only', 'lumination-quiz-generator' ); ?></td>
					<td><code>[lumination_quiz mode="file"]</code></td>
				</tr>
				<tr>
					<td><?php esc_html_e( 'Custom Title', 'lumination-quiz-generator' ); ?></td>
					<td><code>[lumination_quiz title="Study Quiz" description="Test your knowledge"]</code></td>
				</tr>
			</tbody>
		</table>

		<h3 style="margin-top: 1.5em;"><?php esc_html_e( 'Shortcode Parameters', 'lumination-quiz-generator' ); ?></h3>
		<table class="widefat striped" style="max-width: 800px;">
			<thead>
				<tr>
					<th><?php esc_html_e( 'Parameter', 'lumination-quiz-generator' ); ?></th>
					<th><?php esc_html_e( 'Values', 'lumination-quiz-generator' ); ?></th>
					<th><?php esc_html_e( 'Default', 'lumination-quiz-generator' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><code>mode</code></td>
					<td>url, text, file, auto</td>
					<td>auto</td>
				</tr>
				<tr>
					<td><code>title</code></td>
					<td><?php esc_html_e( 'Any text', 'lumination-quiz-generator' ); ?></td>
					<td>AI Quiz Generator</td>
				</tr>
				<tr>
					<td><code>description</code></td>
					<td><?php esc_html_e( 'Any text', 'lumination-quiz-generator' ); ?></td>
					<td><?php esc_html_e( '(default prompt)', 'lumination-quiz-generator' ); ?></td>
				</tr>
				<tr>
					<td><code>button_text</code></td>
					<td><?php esc_html_e( 'Any text', 'lumination-quiz-generator' ); ?></td>
					<td>Generate Quiz</td>
				</tr>
			</tbody>
		</table>

		<div class="card" style="margin-top: 20px;">
			<h2><?php esc_html_e( 'Access Control', 'lumination-quiz-generator' ); ?></h2>
			<p>
				<?php
				printf(
					/* translators: %s: filter name */
					esc_html__( 'By default all visitors can use the tool. To restrict access, filter %s:', 'lumination-quiz-generator' ),
					'<code>lumination_core_can_submit</code>'
				);
				?>
			</p>
			<pre style="background:#f0f0f0;padding:12px;border-radius:4px;overflow-x:auto;font-size:12px;"><?php echo esc_html(
'add_filter( \'lumination_core_can_submit\', function ( $allowed, $capability, $user_id ) {
    if ( \'quiz\' === $capability ) {
        return is_user_logged_in();
    }
    return $allowed;
}, 10, 3 );'
); ?></pre>
		</div>
		<?php
	}
}
